### ISSUE TITLE
Input Repository

### ISSUE THREAD

**Issue by kdumontnu** [Xotl/cool-github-releases#10]
First of all, this project is really well done. Thank you for publishing it.

I'm wondering if you have any plans to add an input option to specify a separate git repository to download release files from, for instance in the form `repo:Xotl/cool-github-releases`.

For me, I manage a utils repository separate from my main app, and need a way to download those assets to my main project when building. This would be the perfect solution if I can pass a different private repo.

Given the way you've set up the action, it seems possible. I'm happy to help out.

**Comment by Xotl** [comment]
Hi @kdumontnu, 

First of all thanks for using my action and thanks a lot for your kind words, i put some love on this action. 😊 

Let me see if this weekend i can have something working. I think that would be a nice feature to have.

PD: Sorry for the late response, i have been quite busy these days.

**Comment by kdumontnu** [comment]
@Xotl, No worries at all - hopefully you're busy because of some interesting projects going on. 

Sounds great! Let me know if I can help in any way.

**Comment by Xotl** [comment]
Hi @kdumontnu,

[Taking a look at the code](https://github.com/Xotl/cool-github-releases/blob/master/src/index.js#L15), it seems that you can specify a different repo and org in the current version of the action. Just set the `GITHUB_REPOSITORY` environment variable with a string with the next form: `<org>/<repo>`.

Example: 
```yaml
      - name: Create new release
        uses: Xotl/cool-github-releases@v1
        env:
          GITHUB_REPOSITORY: Xotl/cool-github-releases
        with:
          mode: download
          tag_name: ${{env.NEW_TAG}}
```

It's not documented since originally it was there for other purposes but you can safely use it. I think i will add a new input for this purpose so the feature looks more integrated into the action (also will document the feature). But probably i will add it later, meanwhile you can use that approach if you need that right away.

If have any questions or issues, please let me know. 😃

**Comment by kdumontnu** [comment]
Awesome. Thanks for taking a look. I couldn't get it to work with by changing the environment variable (not sure why). HOWEVER, I did find that the input option for `repository` is already supported in your app, but not in the documentation - that actually worked for me! 

https://github.com/Xotl/cool-github-releases/blob/ef50014218e6139d534f725f69aabe3728ea9b2e/src/index.js#L15

The action snippet:
```
      - name: Download new release
        uses: Xotl/cool-github-releases@v1
        with:
          mode: download
          repository: Xotl/cool-github-releases
```

**Comment by Xotl** [comment]
Nice!... i will just document the feature. Thanks for noticing. 😅

**Comment by miljan-aleksic** [comment]
@Xotl, @kdumontnu this workaround will actually not work as the `repository` is not declared as a valid action input. I would like to see this supported, though.

**Comment by Xotl** [comment]
Hey @miljan-aleksic, thanks for reporting this.

You are right, that input it's not declared in the `action.yml`. I think i'll have some free time this weekend, so will try to add this feature soon. 

Hope you guys are enjoying this action. 😄

**Comment by Xotl** [comment]
Just to let you know guys that the `repository` input got added to the _action.yml_ and also added some documentation.

Also thanks again for reporting it. 😄

**Comment by miljan-aleksic** [comment]
Thanks @Xotl !!

I think there is some issue in the code, I have set my yaml as:

```
name: Download Joomla Installer
uses: Xotl/cool-github-releases@v1
with:
  repository: org/repo
  assets: installer.zip|dist/temp/installer.zip
  github_token: ${{ secrets.TOKEN }}
```

and getting this error:

```
Run Xotl/cool-github-releases@v1
No tag or id provided: Looking for the latest release.
Starting the download of asset installer.zip...
Download of assets finished successfully.
fs.js:143
    throw new ERR_INVALID_CALLBACK(cb);
    ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined
    at makeCallback (fs.js:143:11)
    at Object.unlink (fs.js:1024:14)
    at WriteStream.l (/home/runner/work/_actions/Xotl/cool-github-releases/v1/dist/index.js:1:37615)
    at WriteStream.emit (events.js:210:5)
    at internal/fs/streams.js:294:12
    at FSReqCallback.oncomplete (fs.js:146:23) {
  code: 'ERR_INVALID_CALLBACK'
}
```
